declare var __DEV__: boolean
declare var __PROD__: boolean
declare var __VERSION__: string
declare namespace NodeJS {
    interface ProcessEnv {
        NVM_INC:string
        STARSHIP_SHELL:string
        MANPATH:string
        TERM_PROGRAM:string
        NODE:string
        INIT_CWD:string
        NVM_CD_FLAGS:string
        TERM:string
        SHELL:string
        HOMEBREW_REPOSITORY:string
        TMPDIR:string
        TERM_PROGRAM_VERSION:string
        NODE_OPTIONS:string
        ZDOTDIR:string
        FIG_NEW_SESSION:string
        ORIGINAL_XDG_CURRENT_DESKTOP:string
        MallocNanoZone:string
        JENV_FORCEJAVAHOME:string
        npm_config_local_prefix:string
        PNPM_HOME:string
        NVM_DIR:string
        USER:string
        COMMAND_MODE:string
        SSH_AUTH_SOCK:string
        __CF_USER_TEXT_ENCODING:string
        npm_execpath:string
        BUN_WHICH_IGNORE_CWD:string
        PATH:string
        DISCORD_TOKEN:string
        npm_package_json:string
        _:string
        VSCODE_INSPECTOR_OPTIONS:string
        LaunchInstanceID:string
        USER_ZDOTDIR:string
        __CFBundleIdentifier:string
        JENV_LOADED:string
        PWD:string
        JAVA_HOME:string
        npm_package_name:string
        LANG:string
        VSCODE_GIT_ASKPASS_EXTRA_ARGS:string
        XPC_FLAGS:string
        JENV_FORCEJDKHOME:string
        npm_package_version:string
        XPC_SERVICE_NAME:string
        VSCODE_INJECTION:string
        JDK_HOME:string
        SHLVL:string
        HOME:string
        VSCODE_GIT_ASKPASS_MAIN:string
        HOMEBREW_PREFIX:string
        STARSHIP_SESSION_KEY:string
        LOGNAME:string
        JENV_SHELL:string
        VSCODE_GIT_IPC_HANDLE:string
        GOPATH:string
        NVM_BIN:string
        BUN_INSTALL:string
        npm_config_user_agent:string
        VSCODE_GIT_ASKPASS_NODE:string
        GIT_ASKPASS:string
        INFOPATH:string
        HOMEBREW_CELLAR:string
        LASTFM_API_KEY:string
        DATABASE_URL:string
        SECURITYSESSIONID:string
        npm_node_execpath:string
        COLORTERM:string
    }
}
